### ISSUE TITLE
Feature request: variables for attributes

### ISSUE THREAD

**Issue by joggs** [bitfocus/companion-module-homeassistant-server#26]
Please correct me if I am wrong, but I do not think it is possible to display attributes for an entity from a home assistant variable?
A feature request would be to implement this.
If Marantz7015 has an attribute called sound_mode, you would enter this:
$(homeassistant-server:entity.media_player.marantz_sr7015.attributes.sound_mode.value)

**Comment by PanicRide** [comment]
I was able to get around this by manually creating a new template sensor in Home Assistant that I can use in bitfocus companion like a regular entity value. Here's what it would look like using your example:

`/config/configuration.yaml`:
```
template:
  - sensor:
    - name: Sound Mode
      state: "{{ (state_attr('media_player.marantz_sr7015', 'sound_mode')) }}"
```
