### ISSUE TITLE
Read out temperature of a thermostat?

### ISSUE THREAD

**Issue by metawops** [bitfocus/companion-module-homeassistant-server#33]
Maybe that's a dumb question ... but I wasn't able to readout the currently set temperature of one of my Lumi thermostats.
In the Template Editor inside the dev tools in Home Assistant I can use this template expression to get that value:
`{{ state_attr('climate.lumi_lumi_airrtc_agl001_thermostat_daszimmer', 'temperature') }}`

However, in Companion there doesn't seem to be an according variable.
I can only find two variable for this entity: `$(homeassistant:entity.climate.lumi_lumi_airrtc_agl001_thermostat_daszimmer.value)` (which just reports the current _mode_ of operation, i.e. "heat" or "off") and `$(homeassistant:entity.climate.lumi_lumi_airrtc_agl001_thermostat_daszimmer)` which just reports the full _name_ of the entity. 🤷‍♂️ 

When I try `$(homeassistant:entity.climate.lumi_lumi_airrtc_agl001_thermostat_daszimmer.temperature)` I just get an "NA" so it's not available.

So, is this simply not possible (yet)? Then consider this a feature request ... 🙈 
Or _is_ it possible? Maybe with the new "Button text expression" mode? Haven't looked into expressions too deeply, yet.

Note that this is an _attribute_, not a _state_. Are attributes generally not (yet) possible to read? 😳 

Any help/hint much appreciated. 🙏

**Comment by daedalist** [comment]
Came here to make this request. My hvac entity presents a number of attributes, in addition to its official state value
![image](https://github.com/bitfocus/companion-module-homeassistant-server/assets/11693391/3ed3fcd6-bf44-4b14-afad-c27fadc042e7)

Ideally, attributes of any entity should be supported, since this is common across Home Assistant

**Comment by Nalum** [comment]
Just got these myself and looking to grab this data too. Any updates on it?

**Comment by metawops** [comment]
This is easy to accomplish.
The principle is: for every attribute of an entity that you want to be able to reference in Companion you need to create a new sensor.

In Home Assistant in your `configuration.yaml` file you need to define a new sensor in the 
```yaml
template:
```
section like this:
```yaml
template:
  - sensor:
      - name: "Thermostat Studio Temperatur"
        unique_id: "ThermostatStudioTemperatur"
        unit_of_measurement: "°C"
        icon: mdi:temperature-celsius
        state: >-
          {{ state_attr('climate.lumi_lumi_airrtc_agl001_thermostat_studio', 'temperature') }}
```

Then, in Companion, if you want to display this value on a button you'd reference it like this, e.g.:

<img width="911" alt="Image" src="https://github.com/user-attachments/assets/f83896c6-ea31-45c2-813b-2574f5e5846c" />

You can, of course, check all your HA sensor values in Companion's Variables tab, too:

<img width="912" alt="Image" src="https://github.com/user-attachments/assets/a10647f6-00a8-4bf5-ba55-872f84a7ae08" />

... and even copy the $(variable) identifier to the clipboard. 😉

Hope this helps!
