### ISSUE TITLE
Request to add Locks

### ISSUE THREAD

**Issue by h4nsen** [bitfocus/companion-module-homeassistant-server#49]
Currently it's only possible to show lock-states via `homeassistant-server:entity.lock.<entity>.value`.

It would be nice to have locks added as real types just as Button, Light, Switch etc. so that it would be possible to lock/unlock entities.

**Comment by PanicRide** [comment]
I had to work around that by making a template switch that turns on whenever the door is unlocked, that way I can see the status of that switch on my companion surface. If you toggle the switch, it will toggle the lock state. Here's what it looks like:

```yaml
switch:
  - platform: template
    switches:
      - front_door_unlocked:
          unique_id: front_door_unlocked
          friendly_name: Front Door Unlocked
          icon_template: mdi:lock
          value_template: "{{ is_state('lock.front_door_lock', 'unlocked') }}"
          turn_on:
            service: lock.unlock
            target:
              entity_id: lock.front_door_lock
          turn_off:
            service: lock.lock
            target:
              entity_id: lock.front_door_lock
```
